// ⚠️ DO NOT EDIT THIS FILE - IT IS PROTECTED BY FIGMA MAKE
// This is a utility for interacting with the kv_store_273c94cc table

import { createClient } from "npm:@supabase/supabase-js@2";

const supabase = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
);

const TABLE_NAME = "kv_store_273c94cc";

export async function get(key: string) {
  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select("value")
    .eq("key", key)
    .single();

  if (error) {
    if (error.code === "PGRST116") {
      return null;
    }
    throw error;
  }

  return data?.value ?? null;
}

export async function set(key: string, value: any) {
  const { error } = await supabase.from(TABLE_NAME).upsert({
    key,
    value,
    updated_at: new Date().toISOString(),
  });

  if (error) throw error;
}

export async function del(key: string) {
  const { error } = await supabase.from(TABLE_NAME).delete().eq("key", key);

  if (error) throw error;
}

export async function mget(keys: string[]) {
  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select("key, value")
    .in("key", keys);

  if (error) throw error;

  return data?.map((row) => row.value) ?? [];
}

export async function mset(entries: Record<string, any>) {
  const rows = Object.entries(entries).map(([key, value]) => ({
    key,
    value,
    updated_at: new Date().toISOString(),
  }));

  const { error } = await supabase.from(TABLE_NAME).upsert(rows);

  if (error) throw error;
}

export async function mdel(keys: string[]) {
  const { error } = await supabase.from(TABLE_NAME).delete().in("key", keys);

  if (error) throw error;
}

export async function getByPrefix(prefix: string) {
  const { data, error } = await supabase
    .from(TABLE_NAME)
    .select("key, value")
    .ilike("key", `${prefix}%`);

  if (error) throw error;

  return data?.map((row) => row.value) ?? [];
}
