/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ooaquvbidcgekdkiadrx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vYXF1dmJpZGNnZWtka2lhZHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NjcxNzAsImV4cCI6MjA4NjI0MzE3MH0.rbN-UsTBxRs0txYb7hw-u42iaTsyOJR4xFNVNvHJkGc"